### PR TITLE
Improve package.json

### PR DESCRIPTION
**Pull request by rosen-vladimirov**
Remove dependencies that are already dependencies of nativescript-angular. After flattening them, they'll be usable in the full project.

### CODE REVIEW

**Comment by rosen-vladimirov** [comment]
ping @hdeshev @vakrilov - do we need the other dependencies here:
```
"@angular/http": "2.0.0-rc.1",
"@angular/router": "2.0.0-rc.1",
```

**Comment by hdeshev** [comment]
@rosen-vladimirov I believe we do need those. It's hard to imagine an Angular app without the router or the http module, and it helps users avoid the hassle of setting those dependencies up manually. (I believe a user from the community proposed we include them in the first place).

**Comment by rosen-vladimirov** [comment]
@hdeshev , if you think they are mandatory, we may include them in `nativescript-angular`. In case we do not want need them there, feel free to merge this PR.

**Comment by hdeshev** [comment]
If we include them in nativescript-angular we make them mandatory, which feels wrong. What's the problem with keeping them in the project template and letting users delete those two lines if they don't want to install the packages?

**Comment by rosen-vladimirov** [comment]
@hdeshev there's no problem, I just do not have rights to merge this PR, so feel free to merge it. I was asking because I was not sure if I should remove them, move them to `nativescript-angular` or keep them this way.

**Comment by ignaciofuentes** [comment]
Is there a reason why you decided to keep the version of nativescript-angular as 0.1.1?
[The latest one](https://www.npmjs.com/package/nativescript-angular) is 0.1.6

**Comment by hdeshev** [comment]
@ignaciofuentes It will likely work with 0.1.6 too.

**Pull request merged**
