### PR TITLE
[Do-not-merge] Fixed imports for Es6 build.

### PR DESCRIPTION
**Pull request by nsndeck**

### CODE REVIEW

**Comment by NathanWalker** [comment]
@vchimev Can the latest master of this template be finally published?
I just pulled this down using the `--ng` flag today and it's still pulling down a super old template which points to `0.2.x` of theme --- ouch - desperate here - been forever - please.

**Comment by NathanWalker** [comment]
@vakrilov @vchimev Additionally doing this:
```
tns create project-name --template https://github.com/NativeScript/template-hello-world-ng.git
```
Fails immediately with this:
Unable to use template https://github.com/NativeScript/template-hello-world-ng.git. Make sure you've specified valid name, github URL or path to local dir.
Error is: version not found: nativescript-angular@1.4.0.

This has been this way for awhile and am just stunned this is left like this :(

**Comment by hdeshev** [comment]
@NathanWalker, I hope I can shed some light here.

Normally we keep the master branch of the template project fully working, but we can't guarantee that it will be like that at all time. To avoid complications with additional build infrastructure, we allow ourselves to "break" it for a bit right before releases, so that we can test it internally using our own NPM repo. I'm using quotation marks here, because we never considered this real breakage as most of the users would still use the working package that is up on NPM. Anyway, having a longer "broken template" window is different this time. We did not get very lucky as the release got delayed after we updated the template.

Usually we release nativescript-angular out of band and don't sync with other NativeScript components like tns-core-modules, tns-android, etc, and we could have released the package on NPM to fix the problem. Unfortunately, this time there are... complications. The latest nativescript-angular package requires TypeScript 2.1, which isn't currently supported by the 2.4 releases of both our runtimes. We have a fix coming out with NativeScript 2.5.

**Comment by NathanWalker** [comment]
Thank you @hdeshev for the clear explanation! Makes sense - looking forward to 2.5!

**Pull request closed without merging**
